moved test to main yml

diff --git a/.github/workflows/Clone-Build-Test.yml b/.github/workflows/Clone-Build-Test.yml
--- a/.github/workflows/Clone-Build-Test.yml
+++ b/.github/workflows/Clone-Build-Test.yml
@@ -33,14 +33,39 @@ jobs:
         run: |
           cd src
           dotnet build --configuration Release --no-restore
-      - name: Test
-        run: |
-          cd src
-          dotnet test --no-restore --verbosity normal --logger:trx --collect:"XPlat Code Coverage" --results-directory ./TestResults
-  yaml-integration-tests-prod:
-    needs: build
-    uses: ./.github/workflows/yaml-integration-tests.yml
-    with: 
-       parameters: 
-         '[{ "environmentId": "10195613-f7d0-4d8e-bc74-f8f6bf1fe7d4", "tenantId": "1557f771-4c8e-4dbd-8b80-dd00a88e833e", "domain": "apps.powerapps.com", "testPlanFile": "../../samples/basicgallery/testPlan.fx.yaml", "outputDirectory": "../../TestResults" }]'
-    secrets: inherit
+      # - name: Test
+      #   run: |
+      #     cd src
+      #     dotnet test --no-restore --verbosity normal --logger:trx --collect:"XPlat Code Coverage" --results-directory ./TestResults
+      - name: Integration Test
+        env:
+            user1Email: '${{ secrets.POWER_PLATFORM_USER }}'
+            user1Password: '${{ secrets.POWER_PLATFORM_PASSWORD }}'
+        run: |   
+          cd TestingPowerPlatform/TestingPowerPlatform/src/PowerAppsTestEngine
+          dotnet build
+          pwsh bin/Debug/net6.0/playwright.ps1 install
+          cd ../../build-pipelines/scripts
+          chmod +x yaml-integration-tests.sh
+          ./yaml-integration-tests.sh "[{ "environmentId": "10195613-f7d0-4d8e-bc74-f8f6bf1fe7d4", "tenantId": "1557f771-4c8e-4dbd-8b80-dd00a88e833e", "domain": "apps.powerapps.com", "testPlanFile": "../../samples/basicgallery/testPlan.fx.yaml", "outputDirectory": "../../TestResults" }]"       # run the script with the parameter, contains logic to run the tests
+      - name: Sample Test Report
+        uses: dorny/test-reporter@v1.5.0
+        if: success() || failure()    # run this step even if previous step failed
+        with:
+          name: Sample Tests          # Name of the check run which will be created
+          path: '**/*.trx'            
+          reporter: dotnet-trx        # Format of test results      
+      - name: Upload a Build Artifact
+        uses: actions/upload-artifact@v2
+        if: ${{always()}}
+        with:
+            name: 'Test Run'
+            path: |
+                **/TestResults/**
+  # yaml-integration-tests-prod:
+  #   needs: build
+  #   uses: ./.github/workflows/yaml-integration-tests.yml
+  #   with: 
+  #      parameters: 
+  #        '[{ "environmentId": "10195613-f7d0-4d8e-bc74-f8f6bf1fe7d4", "tenantId": "1557f771-4c8e-4dbd-8b80-dd00a88e833e", "domain": "apps.powerapps.com", "testPlanFile": "../../samples/basicgallery/testPlan.fx.yaml", "outputDirectory": "../../TestResults" }]'
+  #   secrets: inherit
